[project]
name = "realtime"
version = "0.1.0"
description = "Add a short description here"
authors = ["V <V@fbi.gov>"]
channels = ["conda-forge"]
platforms = ["linux-64"]

[tasks]

[dependencies]
requests = ">=2.31.0,<2.32"
python-dotenv = ">=1.0.0,<1.1"
watchdog = ">=3.0.0,<3.1"
flask-socketio = ">=5.3.6,<5.4"
flask = ">=3.0.1,<3.1"
pigar = ">=0.10.0,<0.11"
