[project]
name = "realtime"
version = "0.1.0"
description = "Add a short description here"
authors = ["V <veronika.m.winters@gmail.com>"]
channels = ["conda-forge"]
platforms = ["linux-64"]

[tasks]
save = "git commit --amend --no-edit"
build_tailwind = { cmd = "npx --yes tailwindcss -i ./src/style.css -o ./static/style.css" }
bun_install = { cmd = "npx --yes bun install" }
esbuild = { cmd = "npx --yes bun build.js", depends_on = ["bun_install"] }
pip_install = "pip install flask_socketio"
dep_install = { depends_on = ["esbuild", "pip_install", "build_tailwind"] }
dev = { cmd = "flask run --debug --host=0.0.0.0", depends_on = ["dep_install"] }

[dependencies]
pip = "23.3.1.*"
requests = "2.31.0.*"
python = "==3.10"
flask = "3.0.0.*"
nodejs = "20.8.1.*"
python-dotenv = "1.0.0.*"
watchdog = "3.0.0.*"
