[project]
name = "realtime"
version = "0.1.0"
description = "Add a short description here"
authors = ["V <veronika.m.winters@gmail.com>"]
channels = ["conda-forge"]
platforms = ["linux-64"]

[tasks]

[dependencies]
pip = "23.3.1.*"
requests = "2.31.0.*"
python = "3.12.0.*"
flask = "3.0.0.*"
